// Apple Silicon 칩을 모듈 박스와 비교 패널로 렌더링하는 브라우저 코드
import m1Image from './assets/M1_clean.webp?inline';
import m2Image from './assets/M2_clean.webp?inline';
import m3Image from './assets/M3_clean.webp?inline';
import m4Image from './assets/M4_clean.webp?inline';
import m5Image from './assets/M5_clean.webp?inline';
const chips = [
  { name: 'M1', type: 'BASELINE', year: 2020, metrics: [100, 100, 100, 100, 100], blocks: [['CPU CLUSTER', '8 CORES', '100', 'green'], ['GPU ARRAY', '7 / 8 CORE', '100', 'amber'], ['NEURAL ENGINE', '16 CORE', '100', 'green'], ['UNIFIED MEMORY', '68 GB/s', '100', 'blue'], ['MEDIA ENGINE', 'H.264 / HEVC', '100', 'blue']] },
  { name: 'M1 Pro', type: 'PRO WORKFLOW', year: 2021, metrics: [125, 135, 140, 130, 120], blocks: [['CPU CLUSTER', '10 CORES', '125', 'green'], ['GPU ARRAY', '14 / 16 CORE', '140', 'amber'], ['NEURAL ENGINE', '16 CORE', '120', 'green'], ['UNIFIED MEMORY', '200 GB/s', '130', 'blue'], ['MEDIA ENGINE', 'PRORES PATH', '130', 'blue']] },
  { name: 'M1 Max', type: 'CREATOR PATH', year: 2021, metrics: [130, 180, 190, 150, 150], blocks: [['CPU CLUSTER', '10 CORES', '130', 'green'], ['GPU ARRAY', '24 / 32 CORE', '190', 'amber'], ['NEURAL ENGINE', '16 CORE', '150', 'green'], ['UNIFIED MEMORY', '400 GB/s', '150', 'blue'], ['MEDIA ENGINE', 'DUAL PRORES', '180', 'blue']] },
  { name: 'M1 Ultra', type: 'STUDIO SCALE', year: 2022, metrics: [135, 260, 300, 220, 240], blocks: [['CPU CLUSTER', '20 CORES', '135', 'green'], ['GPU ARRAY', '48 / 64 CORE', '300', 'amber'], ['NEURAL ENGINE', '32 CORE', '240', 'green'], ['UNIFIED MEMORY', '800 GB/s', '220', 'blue'], ['MEDIA ENGINE', '4X PRORES', '260', 'blue']] },
  { name: 'M2', type: 'BASELINE', year: 2022, metrics: [115, 115, 120, 110, 115], blocks: [['CPU CLUSTER', '8 CORES', '115', 'green'], ['GPU ARRAY', '8 / 10 CORE', '120', 'amber'], ['NEURAL ENGINE', '16 CORE', '115', 'green'], ['UNIFIED MEMORY', '100 GB/s', '110', 'blue'], ['MEDIA ENGINE', 'H.264 / HEVC', '115', 'blue']] },
  { name: 'M2 Pro', type: 'PRO WORKFLOW', year: 2023, metrics: [145, 160, 165, 145, 140], blocks: [['CPU CLUSTER', '10 / 12 CORE', '145', 'green'], ['GPU ARRAY', '16 / 19 CORE', '165', 'amber'], ['NEURAL ENGINE', '16 CORE', '140', 'green'], ['UNIFIED MEMORY', '200 GB/s', '145', 'blue'], ['MEDIA ENGINE', 'PRORES PATH', '160', 'blue']] },
  { name: 'M2 Max', type: 'CREATOR PATH', year: 2023, metrics: [150, 210, 225, 170, 180], blocks: [['CPU CLUSTER', '12 CORE', '150', 'green'], ['GPU ARRAY', '30 / 38 CORE', '225', 'amber'], ['NEURAL ENGINE', '16 CORE', '180', 'green'], ['UNIFIED MEMORY', '400 GB/s', '170', 'blue'], ['MEDIA ENGINE', 'DUAL PRORES', '210', 'blue']] },
  { name: 'M2 Ultra', type: 'STUDIO SCALE', year: 2023, metrics: [155, 300, 345, 250, 280], blocks: [['CPU CLUSTER', '24 CORE', '155', 'green'], ['GPU ARRAY', '60 / 76 CORE', '345', 'amber'], ['NEURAL ENGINE', '32 CORE', '280', 'green'], ['UNIFIED MEMORY', '800 GB/s', '250', 'blue'], ['MEDIA ENGINE', '4X PRORES', '300', 'blue']] },
  { name: 'M3', type: 'BASELINE', year: 2023, metrics: [135, 135, 145, 130, 145], blocks: [['CPU CLUSTER', '8 CORE', '135', 'green'], ['GPU ARRAY', '8 / 10 CORE', '145', 'amber'], ['NEURAL ENGINE', '16 CORE', '145', 'green'], ['UNIFIED MEMORY', '100 GB/s', '130', 'blue'], ['MEDIA ENGINE', 'AV1 DECODE', '135', 'blue']] },
  { name: 'M3 Pro', type: 'PRO WORKFLOW', year: 2023, metrics: [160, 180, 195, 160, 170], blocks: [['CPU CLUSTER', '11 / 12 CORE', '160', 'green'], ['GPU ARRAY', '14 / 18 CORE', '195', 'amber'], ['NEURAL ENGINE', '16 CORE', '170', 'green'], ['UNIFIED MEMORY', '150 GB/s', '160', 'blue'], ['MEDIA ENGINE', 'PRORES PATH', '180', 'blue']] },
  { name: 'M3 Max', type: 'CREATOR PATH', year: 2023, metrics: [170, 240, 270, 195, 220], blocks: [['CPU CLUSTER', '14 / 16 CORE', '170', 'green'], ['GPU ARRAY', '30 / 40 CORE', '270', 'amber'], ['NEURAL ENGINE', '16 CORE', '220', 'green'], ['UNIFIED MEMORY', '400 GB/s', '195', 'blue'], ['MEDIA ENGINE', 'DUAL PRORES', '240', 'blue']] },
  { name: 'M3 Ultra', type: 'STUDIO SCALE', year: 2025, metrics: [180, 340, 400, 290, 340], blocks: [['CPU CLUSTER', '28 CORE', '180', 'green'], ['GPU ARRAY', '60 / 80 CORE', '400', 'amber'], ['NEURAL ENGINE', '32 CORE', '340', 'green'], ['UNIFIED MEMORY', '800 GB/s', '290', 'blue'], ['MEDIA ENGINE', '4X PRORES', '340', 'blue']] },
  { name: 'M4', type: 'BASELINE', year: 2024, metrics: [155, 155, 170, 150, 180], blocks: [['CPU CLUSTER', '10 CORE', '155', 'green'], ['GPU ARRAY', '10 CORE', '170', 'amber'], ['NEURAL ENGINE', '16 CORE', '180', 'green'], ['UNIFIED MEMORY', '120 GB/s', '150', 'blue'], ['MEDIA ENGINE', 'AV1 DECODE', '155', 'blue']] },
  { name: 'M4 Pro', type: 'PRO WORKFLOW', year: 2024, metrics: [185, 215, 235, 190, 220], blocks: [['CPU CLUSTER', '12 / 14 CORE', '185', 'green'], ['GPU ARRAY', '16 / 20 CORE', '235', 'amber'], ['NEURAL ENGINE', '16 CORE', '220', 'green'], ['UNIFIED MEMORY', '273 GB/s', '190', 'blue'], ['MEDIA ENGINE', 'PRORES PATH', '215', 'blue']] },
  { name: 'M4 Max', type: 'CREATOR PATH', year: 2024, metrics: [195, 285, 325, 235, 285], blocks: [['CPU CLUSTER', '14 / 16 CORE', '195', 'green'], ['GPU ARRAY', '32 / 40 CORE', '325', 'amber'], ['NEURAL ENGINE', '16 CORE', '285', 'green'], ['UNIFIED MEMORY', '546 GB/s', '235', 'blue'], ['MEDIA ENGINE', 'DUAL PRORES', '285', 'blue']] },
  { name: 'M5', type: 'CURRENT PATH', year: 2025, metrics: [175, 175, 195, 170, 210], blocks: [['CPU CLUSTER', '10 CORE', '175', 'green'], ['GPU ARRAY', '10 CORE', '195', 'amber'], ['NEURAL ENGINE', '16 CORE', '210', 'green'], ['UNIFIED MEMORY', '153 GB/s', '170', 'blue'], ['MEDIA ENGINE', 'AV1 / PRORES', '175', 'blue']] },
  { name: 'M5 Pro', type: 'PRO WORKFLOW', year: 2025, metrics: [210, 245, 275, 215, 255], blocks: [['CPU CLUSTER', '14 CORE', '210', 'green'], ['GPU ARRAY', '20 CORE', '275', 'amber'], ['NEURAL ENGINE', '16 CORE', '255', 'green'], ['UNIFIED MEMORY', '307 GB/s', '215', 'blue'], ['MEDIA ENGINE', 'PRORES PATH', '245', 'blue']] },
  { name: 'M5 Max', type: 'CREATOR PATH', year: 2025, metrics: [225, 320, 365, 265, 330], blocks: [['CPU CLUSTER', '16 CORE', '225', 'green'], ['GPU ARRAY', '40 CORE', '365', 'amber'], ['NEURAL ENGINE', '16 CORE', '330', 'green'], ['UNIFIED MEMORY', '614 GB/s', '265', 'blue'], ['MEDIA ENGINE', 'DUAL PRORES', '320', 'blue']] },
];
const metricNames = ['CPU SINGLE', 'CPU MULTI', 'GPU GRAPHICS', 'MEMORY BANDWIDTH', 'AI COMPUTE'];
const generationChips = [['M1', m1Image], ['M2', m2Image], ['M3', m3Image], ['M4', m4Image], ['M5', m5Image]].map(([name, image]) => ({ ...chips.find(chip => chip.name === name), image }));
let selected = ['M1', 'M2'];
const $ = selector => document.querySelector(selector);
const chipByName = name => chips.find(chip => chip.name === name);

function moduleMarkup([label, value, score, tone], compact = false) { return `<div class="module ${tone} ${compact ? 'compact' : ''}"><span class="module-port"></span><div class="module-label">${label}</div><strong>${value}</strong><small>${score}% INDEX</small><i style="--fill:${Math.min(Number(score) / 4, 100)}%"></i></div>`; }
function chipMarkup(chip, compact = false) { return `<div class="chip-shell ${compact ? 'compact-shell' : ''}"><div class="chip-shell-head"><b>${chip.name}</b><span>${chip.type}</span><em>${chip.year}</em></div><div class="chip-bus"></div><div class="module-grid">${chip.blocks.map(block => moduleMarkup(block, compact)).join('')}</div><div class="chip-shell-foot"><span>UNIFIED ARCHITECTURE</span><span>${chip.blocks.length} MODULES</span></div></div>`; }
function renderJourney() { $('#journeyTrack').innerHTML = generationChips.map((chip, index) => `<article class="generation-scene"><div class="scene-image-frame"><span class="scene-kicker">ORIGINAL / ${chip.name}</span><img src="${chip.image}" alt="${chip.name} 원본 칩 이미지" decoding="async"><span class="scene-number">0${index + 1}</span></div>${chipMarkup(chip)}</article>`).join(''); }
function renderCatalog() { $('#chipGrid').innerHTML = chips.map(chip => { const active = selected.includes(chip.name); return `<button class="chip-card ${active ? 'selected' : ''}" data-chip="${chip.name}" type="button" aria-pressed="${active}"><span class="card-order">${active ? `0${selected.indexOf(chip.name) + 1}` : '+'}</span>${chipMarkup(chip, true)}<div class="card-meta"><strong>${chip.name}</strong><span>${chip.type} / ${chip.year}</span></div></button>`; }).join(''); document.querySelectorAll('.chip-card').forEach(card => card.addEventListener('click', () => toggleChip(card.dataset.chip))); }
function toggleChip(name) { if (selected.includes(name)) { if (selected.length > 1) selected = selected.filter(item => item !== name); } else selected = [selected[1], name]; renderCatalog(); renderCompare(); $('#compare').scrollIntoView({ behavior: 'smooth', block: 'start' }); }
function renderCompare() { const pair = selected.map(chipByName); $('#leftName').textContent = pair[0].name; $('#rightName').textContent = pair[1].name; $('#compareGrid').innerHTML = pair.map((chip, column) => `<article class="compare-column"><div class="compare-column-head"><span class="live-dot">●</span><div><h3>${chip.name}</h3><small>${chip.type} / ${chip.year}</small></div><b>${column === 0 ? 'TARGET A' : 'TARGET B'}</b></div><div class="compare-modules">${chip.blocks.map(([label, value, score, tone]) => `<div class="compare-module ${tone}"><div><span>${label}</span><strong>${value}</strong></div><small>${score} / REFERENCE INDEX</small><i><b style="width:${Math.min(Number(score) / 4, 100)}%"></b></i></div>`).join('')}</div></article>`).join(''); }
function registerWebMCP() { if (!document.modelContext?.registerTool) return; const controller = new AbortController(); window.macCompareWebMCP = { controller }; const register = async () => { await document.modelContext.registerTool({ name: 'list_mac_chips', description: 'List the Mac chip modules available in the Silicon Atlas dashboard.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async () => ({ chips: chips.map(chip => ({ name: chip.name, type: chip.type, year: chip.year, modules: chip.blocks.map(block => block[0]) })) }) }, { signal: controller.signal }); await document.modelContext.registerTool({ name: 'compare_mac_chips', description: 'Select two chips and return their decomposed module comparison.', inputSchema: { type: 'object', properties: { left: { type: 'string' }, right: { type: 'string' } }, required: ['left', 'right'], additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async input => { const left = chipByName(input.left); const right = chipByName(input.right); if (!left || !right || left.name === right.name) return { ok: false, error: 'Choose two different chip names from list_mac_chips.' }; selected = [left.name, right.name]; renderCatalog(); renderCompare(); return { ok: true, selected, metrics: metricNames.map((metric, index) => ({ metric, left: left.metrics[index], right: right.metrics[index] })) }; } }, { signal: controller.signal }); }; register().catch(error => { window.macCompareWebMCP.error = String(error?.message || error); }); }
$('#resetButton').addEventListener('click', () => { selected = ['M1', 'M2']; renderCatalog(); renderCompare(); });
renderJourney(); renderCatalog(); renderCompare(); registerWebMCP();
