// Apple Silicon 칩을 모듈 박스와 비교 패널로 렌더링하는 브라우저 코드
import m1Image from './assets/M1_clean.webp?inline';
import m2Image from './assets/M2_clean.webp?inline';
import m3Image from './assets/M3_clean.webp?inline';
import m4Image from './assets/M4_clean.webp?inline';
import m5Image from './assets/M5_clean.webp?inline';
const chips = [
  { name: 'M1', type: 'BASELINE', year: 2020, metrics: [100, 100, 100, 100, 100], blocks: [['CPU CLUSTER', '8 CORES', '100', 'green'], ['GPU ARRAY', '7 / 8 CORE', '100', 'amber'], ['NEURAL ENGINE', '16 CORE', '100', 'green'], ['UNIFIED MEMORY', '68 GB/s', '100', 'blue'], ['MEDIA ENGINE', 'H.264 / HEVC', '100', 'blue']] },
  { name: 'M1 Pro', type: 'PRO WORKFLOW', year: 2021, metrics: [125, 135, 140, 130, 120], blocks: [['CPU CLUSTER', '10 CORES', '125', 'green'], ['GPU ARRAY', '14 / 16 CORE', '140', 'amber'], ['NEURAL ENGINE', '16 CORE', '120', 'green'], ['UNIFIED MEMORY', '200 GB/s', '130', 'blue'], ['MEDIA ENGINE', 'PRORES PATH', '130', 'blue']] },
  { name: 'M1 Max', type: 'CREATOR PATH', year: 2021, metrics: [130, 180, 190, 150, 150], blocks: [['CPU CLUSTER', '10 CORES', '130', 'green'], ['GPU ARRAY', '24 / 32 CORE', '190', 'amber'], ['NEURAL ENGINE', '16 CORE', '150', 'green'], ['UNIFIED MEMORY', '400 GB/s', '150', 'blue'], ['MEDIA ENGINE', 'DUAL PRORES', '180', 'blue']] },
  { name: 'M1 Ultra', type: 'STUDIO SCALE', year: 2022, metrics: [135, 260, 300, 220, 240], blocks: [['CPU CLUSTER', '20 CORES', '135', 'green'], ['GPU ARRAY', '48 / 64 CORE', '300', 'amber'], ['NEURAL ENGINE', '32 CORE', '240', 'green'], ['UNIFIED MEMORY', '800 GB/s', '220', 'blue'], ['MEDIA ENGINE', '4X PRORES', '260', 'blue']] },
  { name: 'M2', type: 'BASELINE', year: 2022, metrics: [115, 115, 120, 110, 115], blocks: [['CPU CLUSTER', '8 CORES', '115', 'green'], ['GPU ARRAY', '8 / 10 CORE', '120', 'amber'], ['NEURAL ENGINE', '16 CORE', '115', 'green'], ['UNIFIED MEMORY', '100 GB/s', '110', 'blue'], ['MEDIA ENGINE', 'H.264 / HEVC', '115', 'blue']] },
  { name: 'M2 Pro', type: 'PRO WORKFLOW', year: 2023, metrics: [145, 160, 165, 145, 140], blocks: [['CPU CLUSTER', '10 / 12 CORE', '145', 'green'], ['GPU ARRAY', '16 / 19 CORE', '165', 'amber'], ['NEURAL ENGINE', '16 CORE', '140', 'green'], ['UNIFIED MEMORY', '200 GB/s', '145', 'blue'], ['MEDIA ENGINE', 'PRORES PATH', '160', 'blue']] },
  { name: 'M2 Max', type: 'CREATOR PATH', year: 2023, metrics: [150, 210, 225, 170, 180], blocks: [['CPU CLUSTER', '12 CORE', '150', 'green'], ['GPU ARRAY', '30 / 38 CORE', '225', 'amber'], ['NEURAL ENGINE', '16 CORE', '180', 'green'], ['UNIFIED MEMORY', '400 GB/s', '170', 'blue'], ['MEDIA ENGINE', 'DUAL PRORES', '210', 'blue']] },
  { name: 'M2 Ultra', type: 'STUDIO SCALE', year: 2023, metrics: [155, 300, 345, 250, 280], blocks: [['CPU CLUSTER', '24 CORE', '155', 'green'], ['GPU ARRAY', '60 / 76 CORE', '345', 'amber'], ['NEURAL ENGINE', '32 CORE', '280', 'green'], ['UNIFIED MEMORY', '800 GB/s', '250', 'blue'], ['MEDIA ENGINE', '4X PRORES', '300', 'blue']] },
  { name: 'M3', type: 'BASELINE', year: 2023, metrics: [135, 135, 145, 130, 145], blocks: [['CPU CLUSTER', '8 CORE', '135', 'green'], ['GPU ARRAY', '8 / 10 CORE', '145', 'amber'], ['NEURAL ENGINE', '16 CORE', '145', 'green'], ['UNIFIED MEMORY', '100 GB/s', '130', 'blue'], ['MEDIA ENGINE', 'AV1 DECODE', '135', 'blue']] },
  { name: 'M3 Pro', type: 'PRO WORKFLOW', year: 2023, metrics: [160, 180, 195, 160, 170], blocks: [['CPU CLUSTER', '11 / 12 CORE', '160', 'green'], ['GPU ARRAY', '14 / 18 CORE', '195', 'amber'], ['NEURAL ENGINE', '16 CORE', '170', 'green'], ['UNIFIED MEMORY', '150 GB/s', '160', 'blue'], ['MEDIA ENGINE', 'PRORES PATH', '180', 'blue']] },
  { name: 'M3 Max', type: 'CREATOR PATH', year: 2023, metrics: [170, 240, 270, 195, 220], blocks: [['CPU CLUSTER', '14 / 16 CORE', '170', 'green'], ['GPU ARRAY', '30 / 40 CORE', '270', 'amber'], ['NEURAL ENGINE', '16 CORE', '220', 'green'], ['UNIFIED MEMORY', '400 GB/s', '195', 'blue'], ['MEDIA ENGINE', 'DUAL PRORES', '240', 'blue']] },
  { name: 'M3 Ultra', type: 'STUDIO SCALE', year: 2025, metrics: [180, 340, 400, 290, 340], blocks: [['CPU CLUSTER', '28 CORE', '180', 'green'], ['GPU ARRAY', '60 / 80 CORE', '400', 'amber'], ['NEURAL ENGINE', '32 CORE', '340', 'green'], ['UNIFIED MEMORY', '800 GB/s', '290', 'blue'], ['MEDIA ENGINE', '4X PRORES', '340', 'blue']] },
  { name: 'M4', type: 'BASELINE', year: 2024, metrics: [155, 155, 170, 150, 180], blocks: [['CPU CLUSTER', '10 CORE', '155', 'green'], ['GPU ARRAY', '10 CORE', '170', 'amber'], ['NEURAL ENGINE', '16 CORE', '180', 'green'], ['UNIFIED MEMORY', '120 GB/s', '150', 'blue'], ['MEDIA ENGINE', 'AV1 DECODE', '155', 'blue']] },
  { name: 'M4 Pro', type: 'PRO WORKFLOW', year: 2024, metrics: [185, 215, 235, 190, 220], blocks: [['CPU CLUSTER', '12 / 14 CORE', '185', 'green'], ['GPU ARRAY', '16 / 20 CORE', '235', 'amber'], ['NEURAL ENGINE', '16 CORE', '220', 'green'], ['UNIFIED MEMORY', '273 GB/s', '190', 'blue'], ['MEDIA ENGINE', 'PRORES PATH', '215', 'blue']] },
  { name: 'M4 Max', type: 'CREATOR PATH', year: 2024, metrics: [195, 285, 325, 235, 285], blocks: [['CPU CLUSTER', '14 / 16 CORE', '195', 'green'], ['GPU ARRAY', '32 / 40 CORE', '325', 'amber'], ['NEURAL ENGINE', '16 CORE', '285', 'green'], ['UNIFIED MEMORY', '546 GB/s', '235', 'blue'], ['MEDIA ENGINE', 'DUAL PRORES', '285', 'blue']] },
  { name: 'M5', type: 'CURRENT PATH', year: 2025, metrics: [175, 175, 195, 170, 210], blocks: [['CPU CLUSTER', '10 CORE', '175', 'green'], ['GPU ARRAY', '10 CORE', '195', 'amber'], ['NEURAL ENGINE', '16 CORE', '210', 'green'], ['UNIFIED MEMORY', '153 GB/s', '170', 'blue'], ['MEDIA ENGINE', 'AV1 / PRORES', '175', 'blue']] },
  { name: 'M5 Pro', type: 'PRO WORKFLOW', year: 2025, metrics: [210, 245, 275, 215, 255], blocks: [['CPU CLUSTER', '14 CORE', '210', 'green'], ['GPU ARRAY', '20 CORE', '275', 'amber'], ['NEURAL ENGINE', '16 CORE', '255', 'green'], ['UNIFIED MEMORY', '307 GB/s', '215', 'blue'], ['MEDIA ENGINE', 'PRORES PATH', '245', 'blue']] },
  { name: 'M5 Max', type: 'CREATOR PATH', year: 2025, metrics: [225, 320, 365, 265, 330], blocks: [['CPU CLUSTER', '16 CORE', '225', 'green'], ['GPU ARRAY', '40 CORE', '365', 'amber'], ['NEURAL ENGINE', '16 CORE', '330', 'green'], ['UNIFIED MEMORY', '614 GB/s', '265', 'blue'], ['MEDIA ENGINE', 'DUAL PRORES', '320', 'blue']] },
];
const metricNames = ['CPU SINGLE', 'CPU MULTI', 'GPU GRAPHICS', 'MEMORY BANDWIDTH', 'AI COMPUTE'];
const translations = {
  en: { generationGraph: 'APPLE SILICON / GENERATION GRAPH', scrollToTrace: 'SCROLL TO TRACE ●', chipRegistry: 'CHIP REGISTRY', selectTwo: 'SELECT TWO TARGETS TO INSPECT', knowledgeMap: 'KNOWLEDGE MAP', clickModel: 'CLICK A MODEL TO INSPECT ITS SPECS', comparisonConsole: 'COMPARISON CONSOLE', referenceIndex: 'REFERENCE INDEX / NOT LAB BENCHMARK', activeSilicon: 'ACTIVE SILICON', index: 'INDEX', year: 'YEAR', type: 'TYPE', cpu: 'CPU CLUSTER', gpu: 'GPU ARRAY', neural: 'NEURAL ENGINE', memory: 'UNIFIED MEMORY', media: 'MEDIA ENGINE' },
  ko: { generationGraph: 'Apple Silicon / 세대 그래프', scrollToTrace: '스크롤하여 추적 ●', chipRegistry: '칩 레지스트리', selectTwo: '비교할 두 모델을 선택하세요', knowledgeMap: '지식 맵', clickModel: '모델을 클릭해 상세 스펙을 확인하세요', comparisonConsole: '비교 콘솔', referenceIndex: '참조 지수 / 실험실 벤치마크 아님', activeSilicon: '선택 실리콘', index: '지수', year: '연도', type: '유형', cpu: 'CPU 클러스터', gpu: 'GPU 어레이', neural: '뉴럴 엔진', memory: '통합 메모리', media: '미디어 엔진' },
  ja: { generationGraph: 'Apple Silicon / 世代グラフ', scrollToTrace: 'スクロールして追跡 ●', chipRegistry: 'チップレジストリ', selectTwo: '比較する2つのモデルを選択', knowledgeMap: 'ナレッジマップ', clickModel: 'モデルをクリックして仕様を確認', comparisonConsole: '比較コンソール', referenceIndex: '参照指数 / ラボベンチマークではありません', activeSilicon: '選択中のシリコン', index: '指数', year: '年', type: 'タイプ', cpu: 'CPU クラスター', gpu: 'GPU アレイ', neural: 'ニューラルエンジン', memory: '統合メモリ', media: 'メディアエンジン' },
  zh: { generationGraph: 'Apple Silicon / 世代图', scrollToTrace: '滚动追踪 ●', chipRegistry: '芯片目录', selectTwo: '选择两个目标进行比较', knowledgeMap: '知识地图', clickModel: '点击型号查看详细规格', comparisonConsole: '比较控制台', referenceIndex: '参考指数 / 非实验室基准', activeSilicon: '当前芯片', index: '指数', year: '年份', type: '类型', cpu: 'CPU 集群', gpu: 'GPU 阵列', neural: '神经引擎', memory: '统一内存', media: '媒体引擎' },
};
const pageCopy = {
  en: { stageTitle: 'Mac chip<br><em>runtime map.</em>', stageCopy: 'Trace CPU, GPU, Neural, Memory, and Media paths across every Apple Silicon generation.', activeModule: 'ACTIVE MODULE', memoryMedia: 'MEMORY / MEDIA', computePath: 'COMPUTE PATH', catalogTitle: 'The complete<br><em>silicon lineup.</em>', catalogCopy: 'Explore every M-series chip and select two models to compare their internal architecture.', mapTitle: 'One chip,<br><em>eighteen paths.</em>', mapCopy: 'Follow every M-series model from the central silicon node to its detailed specification profile.', compareCopy: 'Compare the selected chips side by side across their five core modules.', compareFootnote: '* Reference values are for visual generation comparison and are not laboratory benchmarks.', resetView: 'RESET VIEW', confidence: 'CONFIDENCE', top: 'TOP', process: 'PROCESS', generations: 'GENERATIONS', modules: 'MODULES', status: 'STATUS', online: 'ONLINE', footerLeft: 'SILICON ATLAS / CRT CONSOLE', footerRight: 'WEBMCP READY · REDUCED MOTION READY' },
  ko: { stageTitle: 'Mac 칩<br><em>런타임 맵.</em>', stageCopy: 'Apple Silicon 세대별 CPU, GPU, Neural, Memory, Media 경로를 추적합니다.', activeModule: '활성 모듈', memoryMedia: '메모리 / 미디어', computePath: '컴퓨트 경로', catalogTitle: '전체<br><em>실리콘 라인업.</em>', catalogCopy: '모든 M 시리즈 칩을 살펴보고 두 모델을 선택해 내부 아키텍처를 비교하세요.', mapTitle: '하나의 칩,<br><em>열여덟 개의 경로.</em>', mapCopy: '중앙 실리콘 노드에서 모든 M 시리즈 모델의 상세 사양까지 따라가세요.', compareCopy: '선택한 칩의 5개 핵심 모듈을 나란히 비교합니다.', compareFootnote: '* 참조값은 세대 차이를 시각적으로 비교하기 위한 값이며 실험실 벤치마크가 아닙니다.', resetView: '화면 초기화', confidence: '신뢰도', top: '맨 위', process: '프로세스', generations: '세대', modules: '모듈', status: '상태', online: '온라인', footerLeft: 'SILICON ATLAS / CRT 콘솔', footerRight: 'WEBMCP 지원 · 모션 감소 지원' },
  ja: { stageTitle: 'Macチップ<br><em>ランタイムマップ。</em>', stageCopy: 'Apple Siliconの各世代におけるCPU、GPU、Neural、Memory、Mediaの経路を追跡します。', activeModule: 'アクティブモジュール', memoryMedia: 'メモリ / メディア', computePath: 'コンピュート経路', catalogTitle: '完全な<br><em>シリコンラインナップ。</em>', catalogCopy: 'すべてのMシリーズチップを確認し、2つのモデルを選んで内部構成を比較します。', mapTitle: '1つのチップ、<br><em>18の経路。</em>', mapCopy: '中央のシリコンノードから全Mシリーズモデルの詳細仕様まで追跡できます。', compareCopy: '選択したチップの5つの主要モジュールを並べて比較します。', compareFootnote: '* 参照値は世代差を視覚化するためのもので、ラボベンチマークではありません。', resetView: '表示をリセット', confidence: '信頼度', top: 'トップ', process: 'プロセス', generations: '世代', modules: 'モジュール', status: 'ステータス', online: 'オンライン', footerLeft: 'SILICON ATLAS / CRTコンソール', footerRight: 'WebMCP対応 · モーション低減対応' },
  zh: { stageTitle: 'Mac 芯片<br><em>运行时地图。</em>', stageCopy: '追踪每一代 Apple Silicon 的 CPU、GPU、Neural、Memory 和 Media 路径。', activeModule: '活动模块', memoryMedia: '内存 / 媒体', computePath: '计算路径', catalogTitle: '完整的<br><em>芯片阵容。</em>', catalogCopy: '浏览全部 M 系列芯片，选择两个型号比较内部架构。', mapTitle: '一枚芯片，<br><em>十八条路径。</em>', mapCopy: '从中央芯片节点追踪到所有 M 系列型号的详细规格。', compareCopy: '并排比较所选芯片的五个核心模块。', compareFootnote: '* 参考值用于展示世代差异，并非实验室基准测试。', resetView: '重置视图', confidence: '置信度', top: '返回顶部', process: '进程', generations: '世代', modules: '模块', status: '状态', online: '在线', footerLeft: 'SILICON ATLAS / CRT 控制台', footerRight: '支持 WebMCP · 支持减少动态效果' },
};
Object.assign(pageCopy.ko, { stageTitle: 'Mac \uCE69<br><em>\uB7F0\uD0C0\uC784 \uB9F5.</em>', stageCopy: '\uC0C1\uC138\uD55C Apple Silicon \uC138\uB300\uBCC4 CPU, GPU, Neural, Memory, Media \uACBD\ub85c\ub97c \ucd94\uc801\ud569\ub2c8\ub2e4.', catalogTitle: '\uc804\uccb4<br><em>\uc2e4\ub9ac\ucf58 \ub77c\uc778\uc5c5.</em>', catalogCopy: '\ubaa8\ub4e0 M \uc2dc\ub9ac\uc988 \uce69\uc744 \ud0d0\uc0c9\ud558\uace0 \ub450 \ubaa8\ub378\uc744 \uc120\ud0dd\ud574 \ub0b4\ubd80 \uc544\ud0a4\ud14d\ucc98\ub97c \ube44\uad50\ud558\uc138\uc694.', mapTitle: '\ud558\ub098\uc758 \uce69,<br><em>\uc5f4\uc5ec\ub35f \uac1c\uc758 \uacbd\ub85c.</em>', mapCopy: '\uc911\uc559 \uc2e4\ub9ac\ucf58 \ub178\ub4dc\uc5d0\uc11c \ubaa8\ub4e0 M \uc2dc\ub9ac\uc988 \ubaa8\ub378\uc758 \uc0c1\uc138 \uc0ac\uc591\uae4c\uc9c0 \ub530\ub77c\uac00\uc138\uc694.', compareCopy: '\uc120\ud0dd\ud55c \uce69\uc758 5\uac1c \ud575\uc2ec \ubaa8\ub4c8\uc744 \ub098\ub780\ud788 \ube44\uad50\ud569\ub2c8\ub2e4.', compareFootnote: '* \ucc38\uc870\uac12\uc740 \uc138\ub300 \ucc28\uc774\ub97c \uc2dc\uac01\uc801\uc73c\ub85c \ube44\uad50\ud558\uae30 \uc704\ud55c \uac12\uc774\uba70 \uc2e4\ud5d8\uc2e4 \ubca4\uce58\ub9c8\ud06c\uac00 \uc544\ub2d9\ub2c8\ub2e4.' });
Object.assign(pageCopy.ja, { stageTitle: 'Mac\u30c1\u30c3\u30d7<br><em>\u30e9\u30f3\u30bf\u30a4\u30e0\u30de\u30c3\u30d7\u3002</em>', stageCopy: '\u3059\u3079\u3066\u306e Apple Silicon \u4e16\u4ee3\u3067 CPU\u3001GPU\u3001Neural\u3001Memory\u3001Media \u306e\u7d4c\u8def\u3092\u8ffd\u8de1\u3057\u307e\u3059\u3002', catalogTitle: '\u5b8c\u5168\u306a<br><em>\u30b7\u30ea\u30b3\u30f3\u30e9\u30a4\u30f3\u30ca\u30c3\u30d7\u3002</em>', catalogCopy: '\u3059\u3079\u3066\u306e M \u30b7\u30ea\u30fc\u30ba\u30c1\u30c3\u30d7\u3092\u78ba\u8a8d\u3057\u30012\u3064\u306e\u30e2\u30c7\u30eb\u3092\u9078\u3093\u3067\u6bd4\u8f03\u3057\u307e\u3059\u3002', mapTitle: '1\u3064\u306e\u30c1\u30c3\u30d7\u3001<br><em>18\u306e\u7d4c\u8def\u3002</em>', mapCopy: '\u4e2d\u592e\u306e\u30b7\u30ea\u30b3\u30f3\u30ce\u30fc\u30c9\u304b\u3089\u5168 M \u30b7\u30ea\u30fc\u30ba\u30e2\u30c7\u30eb\u306e\u8a73\u7d30\u4ed5\u69d8\u307e\u3067\u8ffd\u8de1\u3067\u304d\u307e\u3059\u3002', compareCopy: '\u9078\u629e\u3057\u305f\u30c1\u30c3\u30d7\u306e5\u3064\u306e\u4e3b\u8981\u30e2\u30b8\u30e5\u30fc\u30eb\u3092\u4e26\u3079\u3066\u6bd4\u8f03\u3057\u307e\u3059\u3002', compareFootnote: '* \u53c2\u7167\u5024\u306f\u4e16\u4ee3\u5dee\u3092\u8996\u899a\u5316\u3059\u308b\u305f\u3081\u306e\u3082\u306e\u3067\u3001\u30e9\u30dc\u30d9\u30f3\u30c1\u30de\u30fc\u30af\u3067\u306f\u3042\u308a\u307e\u305b\u3093\u3002' });
Object.assign(pageCopy.zh, { stageTitle: 'Mac \u82af\u7247<br><em>\u8fd0\u884c\u65f6\u5730\u56fe\u3002</em>', stageCopy: '\u8ffd\u8e2a\u6bcf\u4e00\u4ee3 Apple Silicon \u7684 CPU\u3001GPU\u3001Neural\u3001Memory \u548c Media \u8def\u5f84\u3002', catalogTitle: '\u5b8c\u6574\u7684<br><em>\u82af\u7247\u9635\u5bb9\u3002</em>', catalogCopy: '\u6d4f\u89c8\u5168\u90e8 M \u7cfb\u5217\u82af\u7247\uff0c\u9009\u62e9\u4e24\u4e2a\u578b\u53f7\u6bd4\u8f83\u5185\u90e8\u67b6\u6784\u3002', mapTitle: '\u4e00\u679a\u82af\u7247\uff0c<br><em>\u5341\u516b\u6761\u8def\u5f84\u3002</em>', mapCopy: '\u4ece\u4e2d\u592e\u82af\u7247\u8282\u70b9\u8ffd\u8e2a\u5230\u6240\u6709 M \u7cfb\u5217\u578b\u53f7\u7684\u8be6\u7ec6\u89c4\u683c\u3002', compareCopy: '\u5e76\u6392\u6bd4\u8f83\u6240\u9009\u82af\u7247\u7684\u4e94\u4e2a\u6838\u5fc3\u6a21\u5757\u3002', compareFootnote: '* \u53c2\u8003\u503c\u7528\u4e8e\u5c55\u793a\u4e16\u4ee3\u5dee\u5f02\uff0c\u5e76\u975e\u5b9e\u9a8c\u5ba4\u57fa\u51c6\u6d4b\u8bd5\u3002' });
const supportedLanguages = Object.keys(translations);
const browserLanguage = [...(navigator.languages || []), navigator.language].find(value => supportedLanguages.includes(value?.split('-')[0]));
let language = localStorage.getItem('silicon-atlas-language') || browserLanguage?.split('-')[0] || 'en';
const t = key => pageCopy[language]?.[key] || translations[language][key] || pageCopy.en?.[key] || translations.en[key] || key;
const localizedNodes = { '.stage-copy h1': 'stageTitle', '.stage-copy p': 'stageCopy', '.stage-legend span:nth-child(1)': 'activeModule', '.stage-legend span:nth-child(2)': 'memoryMedia', '.stage-legend span:nth-child(3)': 'computePath', '#catalogTitle': 'catalogTitle', '#catalog .section-heading p': 'catalogCopy', '#knowledgeMapTitle': 'mapTitle', '#knowledgeMapSection .knowledge-map-head p': 'mapCopy', '#compare .compare-heading p': 'compareCopy', '.compare-footnote': 'compareFootnote', '#resetButton': 'resetView', '.map-orb small': 'confidence', '.top-button': 'top', '.hud span:nth-child(2)': 'process', '.hud span:nth-child(3)': 'generations', '.hud span:nth-child(4)': 'modules', '.hud span:nth-child(5)': 'status', '.footer span:nth-child(1)': 'footerLeft', '.footer span:nth-child(2)': 'footerRight' };
Object.entries(localizedNodes).forEach(([selector, key]) => { const node = document.querySelector(selector); if (node) { node.dataset.i18n = key; if (key === 'stageTitle' || key === 'catalogTitle' || key === 'mapTitle') node.dataset.i18nHtml = 'true'; } });
function applyLanguage() { document.documentElement.lang = language; document.title = `Silicon Atlas / ${t('knowledgeMap')}`; document.querySelectorAll('[data-i18n]').forEach(node => { if (node.dataset.i18nHtml) node.innerHTML = t(node.dataset.i18n); else if (node.querySelector('b')) node.firstChild.textContent = `${t(node.dataset.i18n)} `; else node.textContent = t(node.dataset.i18n); }); renderKnowledgeMap(); }
const generationChips = [['M1', m1Image], ['M2', m2Image], ['M3', m3Image], ['M4', m4Image], ['M5', m5Image]].map(([name, image]) => ({ ...chips.find(chip => chip.name === name), image }));
let selected = ['M1', 'M2'];
const $ = selector => document.querySelector(selector);
const chipByName = name => chips.find(chip => chip.name === name);

function moduleMarkup([label, value, score, tone], compact = false) { return `<div class="module ${tone} ${compact ? 'compact' : ''}"><span class="module-port"></span><div class="module-label">${label}</div><strong>${value}</strong><small>${score}% INDEX</small><i style="--fill:${Math.min(Number(score) / 4, 100)}%"></i></div>`; }
function chipMarkup(chip, compact = false) { return `<div class="chip-shell ${compact ? 'compact-shell' : ''}"><div class="chip-shell-head"><b>${chip.name}</b><span>${chip.type}</span><em>${chip.year}</em></div><div class="chip-bus"></div><div class="module-grid">${chip.blocks.map(block => moduleMarkup(block, compact)).join('')}</div><div class="chip-shell-foot"><span>UNIFIED ARCHITECTURE</span><span>${chip.blocks.length} MODULES</span></div></div>`; }
function renderJourney() { $('#journeyTrack').innerHTML = generationChips.map(chip => `<article class="generation-scene"><div class="scene-image-frame"><img src="${chip.image}" alt="${chip.name} 원본 칩 이미지" decoding="async"></div>${chipMarkup(chip)}</article>`).join(''); }
function renderCatalog() {
  const families = [...new Set(chips.map(chip => chip.name.split(' ')[0]))];
  $('#chipGrid').innerHTML = families.map(family => {
    const familyChips = chips.filter(chip => chip.name === family || chip.name.startsWith(`${family} `));
    return `<section class="model-branch" aria-labelledby="family-${family}"><div class="branch-root"><span class="branch-pulse"></span><strong id="family-${family}">${family}</strong><small>${familyChips.length} MODELS</small></div><div class="branch-line"></div><div class="branch-leaves">${familyChips.map(chip => { const active = selected.includes(chip.name); return `<button class="chip-card ${active ? 'selected' : ''}" data-chip="${chip.name}" type="button" aria-pressed="${active}"><span class="card-order">${active ? `0${selected.indexOf(chip.name) + 1}` : '+'}</span>${chipMarkup(chip, true)}<div class="card-meta"><strong>${chip.name}</strong><span>${chip.type} / ${chip.year}</span></div></button>`; }).join('')}</div></section>`;
  }).join('');
  document.querySelectorAll('.chip-card').forEach(card => card.addEventListener('click', () => toggleChip(card.dataset.chip)));
}
function toggleChip(name) { if (selected.includes(name)) { if (selected.length > 1) selected = selected.filter(item => item !== name); } else selected = [selected[1], name]; renderCatalog(); renderCompare(); renderKnowledgeMap(); $('#compare').scrollIntoView({ behavior: 'smooth', block: 'start' }); }
function renderCompare() { const pair = selected.map(chipByName); $('#leftName').textContent = pair[0].name; $('#rightName').textContent = pair[1].name; $('#compareGrid').innerHTML = pair.map((chip, column) => `<article class="compare-column"><div class="compare-column-head"><span class="live-dot">●</span><div><h3>${chip.name}</h3><small>${chip.type} / ${chip.year}</small></div><b>${column === 0 ? 'TARGET A' : 'TARGET B'}</b></div><div class="compare-modules">${chip.blocks.map(([label, value, score, tone]) => `<div class="compare-module ${tone}"><div><span>${label}</span><strong>${value}</strong></div><small>${score} / REFERENCE INDEX</small><i><b style="width:${Math.min(Number(score) / 4, 100)}%"></b></i></div>`).join('')}</div></article>`).join(''); }
let mapChipActive = 'M1';
function renderKnowledgeMap() {
  const chip = chipByName(mapChipActive) || chips[0];
  const average = Math.round(chip.metrics.reduce((sum, value) => sum + value, 0) / chip.metrics.length);
  $('#mapChipName').textContent = chip.name;
  $('#mapConfidence').textContent = `${Math.min(99, 78 + Math.round(average / 20))}%`;
  const moduleKeys = ['cpu', 'gpu', 'neural', 'memory', 'media'];
  $('#mapDetail').innerHTML = `<div class="map-detail-kicker">${t('activeSilicon')} / ${chip.year}</div><h3>${chip.name}</h3><strong>${chip.type}</strong><div class="map-spec-list">${chip.blocks.map(([label, value, score, tone], index) => `<div class="map-spec ${tone}"><span>${t(moduleKeys[index])}</span><b>${value}</b><i><em style="width:${Math.min(Number(score) / 4, 100)}%"></em></i></div>`).join('')}</div>`;
  $('#mapCards').innerHTML = chips.map((model, index) => { const active = model.name === chip.name; return `<button class="model-map-card ${active ? 'active' : ''}" data-map-chip="${model.name}" type="button" aria-pressed="${active}"><span class="map-card-index">${String(index + 1).padStart(2, '0')}</span><span class="map-card-label">${model.name.split(' ')[0]}</span><strong>${model.name}</strong><small>${model.type} · ${model.year}</small><i><b style="width:${Math.min(Number(model.metrics[0]) / 4, 100)}%"></b></i></button>`; }).join('');
  $('#mapWireGroup').innerHTML = chips.map((model, index) => { const column = index % 3; const row = Math.floor(index / 3); const endX = 760 + column * 145; const endY = 70 + row * 100; const active = model.name === chip.name; return `<path class="map-wire ${active ? 'active' : ''}" data-map-wire="${model.name}" d="M430 340 C540 340 ${endX - 150} ${endY} ${endX} ${endY}"></path>`; }).join('');
  document.querySelectorAll('.model-map-card').forEach(card => card.addEventListener('click', () => { mapChipActive = card.dataset.mapChip; renderKnowledgeMap(); }));
}
function registerWebMCP() { if (!document.modelContext?.registerTool) return; const controller = new AbortController(); window.macCompareWebMCP = { controller }; const register = async () => { await document.modelContext.registerTool({ name: 'list_mac_chips', description: 'List the Mac chip modules available in the Silicon Atlas dashboard.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async () => ({ chips: chips.map(chip => ({ name: chip.name, type: chip.type, year: chip.year, modules: chip.blocks.map(block => block[0]) })) }) }, { signal: controller.signal }); await document.modelContext.registerTool({ name: 'compare_mac_chips', description: 'Select two chips and return their decomposed module comparison.', inputSchema: { type: 'object', properties: { left: { type: 'string' }, right: { type: 'string' } }, required: ['left', 'right'], additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async input => { const left = chipByName(input.left); const right = chipByName(input.right); if (!left || !right || left.name === right.name) return { ok: false, error: 'Choose two different chip names from list_mac_chips.' }; selected = [left.name, right.name]; renderCatalog(); renderCompare(); renderKnowledgeMap(); return { ok: true, selected, metrics: metricNames.map((metric, index) => ({ metric, left: left.metrics[index], right: right.metrics[index] })) }; } }, { signal: controller.signal }); }; register().catch(error => { window.macCompareWebMCP.error = String(error?.message || error); }); }
$('#resetButton').addEventListener('click', () => { selected = ['M1', 'M2']; renderCatalog(); renderCompare(); renderKnowledgeMap(); });
$('#topButton').addEventListener('click', () => $('#top').scrollIntoView({ behavior: 'smooth', block: 'start' }));
$('#languageSelect').value = language;
$('#languageSelect').addEventListener('change', event => { language = event.target.value; localStorage.setItem('silicon-atlas-language', language); applyLanguage(); });
const railSections = ['top', 'catalog', 'knowledgeMapSection', 'compare'].map(id => document.getElementById(id));
const railLinks = [...document.querySelectorAll('.section-rail-link')];
const railObserver = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) railLinks.forEach((link, index) => link.classList.toggle('active', railSections[index] === entry.target)); }), { rootMargin: '-35% 0px -55% 0px' });
railSections.forEach(section => railObserver.observe(section));
renderJourney(); renderCatalog(); renderCompare(); renderKnowledgeMap(); applyLanguage(); registerWebMCP();
